run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    confidence: 0.8
  govet:
    enable-all: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
